GET http://localhost:3000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkSmowa2hub2tLajZPZlJxSlpMbG5tdTFPZW1SMWhCdFl5VWN3UjZGaDBxVnZrS3BnQVQvUVciLCJuYW1lIjoidGVzdGFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xNFQxMDo0MDozOS41MjZaIiwicm9sZSI6IkFETUlOIiwiaXNCYW5uZWQiOmZhbHNlfSwiaWF0IjoxNzI5MTU4NzEyLCJleHAiOjE3MjkxNjIzMTJ9.8oegsCm2XVVxErLD3AGZuorFEFEXswSjvSK4FJtAGdo
### only ADMIN