GET http://localhost:3000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJ1c2VybmFtZSI6InRlc3Q0IiwicGFzc3dvcmQiOiIkMmIkMTAkNVVZNHRsMXZUaElWQ3A4OUtVSlNQLlo0Ni5TWVg1aTBBQTRsV2tVQjRSeXRYVURTai5mNzIiLCJuYW1lIjoidGVzdHVzZXIiLCJjcmVhdGVkQXQiOiIyMDI0LTEwLTE1VDA5OjI1OjMyLjAzMVoiLCJyb2xlIjoiVVNFUiIsImlzQmFubmVkIjp0cnVlfSwiaWF0IjoxNzI5MTUzODUzLCJleHAiOjE3MjkxNTc0NTN9.SI4uwAOrd9keEBw2c6qESgLBkI8nx1eKm4mCtxDcwQE
### only ADMIN