PATCH http://localhost:3000/api/v1/users/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkSmowa2hub2tLajZPZlJxSlpMbG5tdTFPZW1SMWhCdFl5VWN3UjZGaDBxVnZrS3BnQVQvUVciLCJuYW1lIjoidGVzdGFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xNFQxMDo0MDozOS41MjZaIiwicm9sZSI6IkFETUlOIiwiaXNCYW5uZWQiOmZhbHNlfSwiaWF0IjoxNzI5MTU0MzIxLCJleHAiOjE3MjkxNTc5MjF9.shjo8r2kMUzrCxzXSCiL6lgRMMW03maDU5ZUzjhfXhY

{
    "role": "USER",
    "isBanned": true
}

### only ADMIN