GET http://localhost:3000/api/v1/publications
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJ1c2VybmFtZSI6InRlc3Q0IiwicGFzc3dvcmQiOiIkMmIkMTAkNVVZNHRsMXZUaElWQ3A4OUtVSlNQLlo0Ni5TWVg1aTBBQTRsV2tVQjRSeXRYVURTai5mNzIiLCJuYW1lIjoidGVzdHVzZXIiLCJjcmVhdGVkQXQiOiIyMDI0LTEwLTE1VDA5OjI1OjMyLjAzMVoiLCJyb2xlIjoiVVNFUiIsImlzQmFubmVkIjp0cnVlfSwiaWF0IjoxNzI5MTU4ODUwLCJleHAiOjE3MjkxNjI0NTB9.8Avrb-GHe67SH5UVZwAwgp1l9rdc71t7Z2DXbEBs_4s