POST http://localhost:3000/api/v1/publications
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QzIiwiaWF0IjoxNzI4OTgyNTQyLCJleHAiOjE3Mjg5ODYxNDJ9.0Q5V6Ks9he5YO0bLtssry993Oi4cG1URelQmC6RufW4

{
    "title": "Test Title",
    "content": "Test Content",
    "authorname": "test1"
}