name: Blog App CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: mysql://testuser:testpassword@mysql:3306/testdb

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"

    - name: Install dependencies backend
      run: cd server && npm install

    - name: Build backend
      run: cd server && npm run build

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h "mysql" -P 3306 --silent; then
            echo "MySQL is up!"
            break
          fi
          sleep 2
        done

    - name: Run Prisma Migrations
      run: cd server && npx prisma migrate deploy
      env:
        DATABASE_URL: ${{ env.DATABASE_URL }}

    - name: Test DB Connection
      run: mysql -hmysql -utestuser -ptestpassword -e "SHOW DATABASES;"

    - name: Run tests
      run: cd server && npm test
      env:
        DATABASE_URL: ${{ env.DATABASE_URL }}